import type { Profile } from "../x/profile";
import type { Timeline, Tweet } from "../x/timeline";

const GUID_CUTOFF = 2000000000000000000n;

export function renderTimelineRss(profile: Profile, timeline: Timeline, origin: string): string {
  const handle = `@${profile.username}`;
  const title = xmlEscape(`${profile.name} / ${handle}`);
  const items = [timeline.pinned, ...timeline.tweets]
    .filter((tweet): tweet is Tweet => Boolean(tweet))
    .filter((tweet, index, all) => all.findIndex((item) => item.id === tweet.id) === index)
    .map((tweet) => renderRssTweet(tweet, origin))
    .join("");

  return `<?xml version="1.0" encoding="UTF-8"?>
<rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:dc="http://purl.org/dc/elements/1.1/" version="2.0">
  <channel>
    <atom:link href="${xmlEscape(`${origin}/${profile.username}/rss`)}" rel="self" type="application/rss+xml" />
    <title>${title}</title>
    <link>${xmlEscape(`${origin}/${profile.username}`)}</link>
    <description>Twitter feed for: ${xmlEscape(handle)}. Generated by ${xmlEscape(origin)}</description>
    <language>en-us</language>
    <ttl>40</ttl>
${profile.avatar ? `    <image>
      <title>${title}</title>
      <link>${xmlEscape(`${origin}/${profile.username}`)}</link>
      <url>${xmlEscape(mediaAbsolute(profile.avatar, origin))}</url>
      <width>128</width>
      <height>128</height>
    </image>
` : ""}${items}  </channel>
</rss>`;
}

function renderRssTweet(source: Tweet, origin: string): string {
  const tweet = source.retweet ?? source;
  const retweet = source.retweet ? source.author.username : "";
  const link = `/${encodeURIComponent(tweet.author.username)}/status/${tweet.id}`;
  const globalGuid = BigInt(tweet.id) >= GUID_CUTOFF;
  const text = stripMediaLinks(tweet);

  return `      <item>
        <title>${rssTitle(tweet, retweet)}</title>
        <dc:creator>@${xmlEscape(tweet.author.username)}</dc:creator>
        <description><![CDATA[<p>${cdataSafe(text).replaceAll("\n", "<br>\n")}</p>${rssMedia(tweet, origin)}${rssQuote(tweet, origin)}]]></description>
        <pubDate>${rfc822(tweet.createdAt)}</pubDate>
        <guid${globalGuid ? ' isPermaLink="false"' : ""}>${globalGuid ? tweet.id : xmlEscape(origin + link)}</guid>
        <link>${xmlEscape(origin + link)}</link>
      </item>
`;
}

function rssTitle(tweet: Tweet, retweet: string): string {
  let prefix = "";
  if (tweet.pinned) prefix = "Pinned: ";
  else if (retweet) prefix = `RT by @${retweet}: `;
  else if (tweet.replyTo.length) prefix = `R to @${tweet.replyTo[0]}: `;
  return xmlEscape(prefix + collapse(tweet.text).slice(0, 64));
}

function rssMedia(tweet: Tweet, origin: string): string {
  if (!tweet.media.length) return "";
  return tweet.media
    .map((item) => {
      if (item.kind === "photo" && item.url) {
        return `<img src="${mediaAbsolute(item.url, origin)}" style="max-width:250px;" />`;
      }
      const preview = item.preview || item.url;
      if (!preview) return "";
      return `<a href="${xmlEscape(origin)}/${encodeURIComponent(tweet.author.username)}/status/${tweet.id}"><br>Video<br><img src="${mediaAbsolute(preview, origin)}" style="max-width:250px;" /></a>`;
    })
    .join("\n");
}

function rssQuote(tweet: Tweet, origin: string): string {
  if (!tweet.quote) return "";
  const quote = tweet.quote;
  const quoteLink = `${origin}/${encodeURIComponent(quote.author.username)}/status/${quote.id}`;
  const quoteText = cdataSafe(xmlEscape(quote.text)).replaceAll("\n", "<br>\n");
  const quoteMedia = quote.media.length
    ? quote.media
        .map((item) => {
          const image = item.kind === "photo" ? item.url : item.preview;
          return image ? `<img src="${mediaAbsolute(image, origin)}" style="max-width:250px;" />` : "";
        })
        .join("")
    : "";
  return `<hr/><blockquote><b>${xmlEscape(quote.author.name)} (@${xmlEscape(quote.author.username)})</b><p>${quoteText}</p>${quoteMedia}<footer><a href="${xmlEscape(quoteLink)}">${xmlEscape(quoteLink)}</a></footer></blockquote>`;
}

function stripMediaLinks(tweet: Tweet): string {
  return cdataSafe(xmlEscape(tweet.text));
}

function cdataSafe(value: string): string {
  return value.replaceAll("]]>", "]]]]><![CDATA[>");
}

function mediaAbsolute(url: string, origin: string): string {
  return `${origin}/media?url=${encodeURIComponent(url)}`;
}

function rfc822(value: string): string {
  const date = new Date(value);
  if (Number.isNaN(date.getTime())) return "";
  return date.toUTCString();
}

function collapse(value: string): string {
  return value.split(/\s+/).filter(Boolean).join(" ");
}

function xmlEscape(value: string): string {
  return value
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&apos;");
}
