import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";

function git(...args) {
  return execFileSync("git", args, { encoding: "utf8" }).trim();
}

const commit = process.env.CF_PAGES_COMMIT_SHA || git("rev-parse", "HEAD");
const shortCommit = git("rev-parse", "--short", commit);
const date = git("show", "-s", "--format=%cd", "--date=format:%Y.%m.%d", commit);
const output = `// Generated by scripts/generate-version.mjs. Do not edit.
export const INSTANCE_VERSION = ${JSON.stringify(`${date}-${shortCommit}`)};
export const INSTANCE_COMMIT_URL = ${JSON.stringify(`https://github.com/UjuiUjuMandan/nitterts/commit/${shortCommit}`)};
`;

mkdirSync("src/generated", { recursive: true });
writeFileSync("src/generated/version.ts", output);
