import { mkdirSync, readFileSync, writeFileSync } from "node:fs";

const markdown = readFileSync("about.md", "utf8");
const output = `// Generated by scripts/generate-about.mjs from about.md. Do not edit.
export const ABOUT_MARKDOWN = ${JSON.stringify(markdown)};
`;

mkdirSync("src/generated", { recursive: true });
writeFileSync("src/generated/about.ts", output);
